# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

msi = Mission.create([{title: 'TOEIC600点以上を取りたい', progress: 1}])

msi1 = Mission.find(1)
smsi = SubMission.create([{mission: msi1, content: '目標設定'}])
smsi = SubMission.create([{mission: msi1, content: '学習計画立案'}])
smsi = SubMission.create([{mission: msi1, content: '学習実施'}])
smsi = SubMission.create([{mission: msi1, content: '模擬試験受験'}])
smsi = SubMission.create([{mission: msi1, content: 'フィードバックと調整'}])
smsi = SubMission.create([{mission: msi1, content: '目標点数を600以上に設定'}])
smsi = SubMission.create([{mission: msi1, content: 'スキルの強化項目を特定'}])
smsi = SubMission.create([{mission: msi1, content: '期限を設定'}])
smsi = SubMission.create([{mission: msi1, content: '学習資材の選定'}])
smsi = SubMission.create([{mission: msi1, content: '学習の意義を明確化'}])
smsi = SubMission.create([{mission: msi1, content: '週間学習スケジュール作成'}])
smsi = SubMission.create([{mission: msi1, content: '学習資材の整理'}])
smsi = SubMission.create([{mission: msi1, content: '学習資材の決定'}])
smsi = SubMission.create([{mission: msi1, content: 'サポート体制を整える'}])
smsi = SubMission.create([{mission: msi1, content: 'モチベーション維持計画策定'}])
smsi = SubMission.create([{mission: msi1, content: '毎日一定の時間を学習に割く'}])
smsi = SubMission.create([{mission: msi1, content: '各スキルごとに練習'}])
smsi = SubMission.create([{mission: msi1, content: 'リスニングとリーディングの練習'}])
smsi = SubMission.create([{mission: msi1, content: 'スピーキングとライティングの練習'}])
smsi = SubMission.create([{mission: msi1, content: '文法と語彙の強化'}])
smsi = SubMission.create([{mission: msi1, content: '模擬試験を受験'}])
smsi = SubMission.create([{mission: msi1, content: '試験時間内で解答'}])
smsi = SubMission.create([{mission: msi1, content: '誤答と難問の解析'}])
smsi = SubMission.create([{mission: msi1, content: 'スコアの記録'}])
smsi = SubMission.create([{mission: msi1, content: '周毎に進捗を確認'}])
smsi = SubMission.create([{mission: msi1, content: '誤答ポイントの特定'}])
smsi = SubMission.create([{mission: msi1, content: '学習計画の調整'}])
smsi = SubMission.create([{mission: msi1, content: '模擬試験結果に基づく練習'}])
smsi = SubMission.create([{mission: msi1, content: 'モチベーションの再評価'}])
smsi = SubMission.create([{mission: msi1, content: '継続的なフィードバック'}])
